/** Auto-generated by scripts/enterprise-ai-apps/generate-dashboard-registry.mjs */

export const ENTERPRISE_DASHBOARD_TEMPLATE_IDS = [
    "supply-chain",
    "compliance-audit",
    "finance",
    "operations",
    "project-service",
    "sustainability",
] as const;

export type EnterpriseDashboardTemplateId = (typeof ENTERPRISE_DASHBOARD_TEMPLATE_IDS)[number];

export type EnterpriseDashboardKpiSlot = {
    metric: string;
    label: string;
};

export type EnterpriseDashboardChartId =
    | "trendArea"
    | "riskDonut"
    | "domainBars"
    | "domainQuadrant"
    | "domainEsgBars"
    | "topRules"
    | "statusPie"
    | "batchStack"
    | "batchTimeline"
    | "recentBatches"
    | "agingStack"
    | "repairTrend";

export type EnterpriseDashboardConfig = {
    appId: string;
    template: EnterpriseDashboardTemplateId;
    hue: number;
    icon: string;
    healthScoreLabel: string;
    batchLabel: string;
    heroChart: EnterpriseDashboardChartId;
    accentChart: EnterpriseDashboardChartId;
    domainChartTitle: string;
    trendChartTitle: string;
    kpis: EnterpriseDashboardKpiSlot[];
    tablePrefix: string;
};

export const ENTERPRISE_DASHBOARD_BY_APP_ID: Record<string, EnterpriseDashboardConfig> = {
    "inv-opt-ai": {
            "appId": "inv-opt-ai",
            "template": "supply-chain",
            "hue": 217,
            "icon": "inventory",
            "healthScoreLabel": "库存健康分",
            "batchLabel": "分析批次",
            "heroChart": "domainBars",
            "accentChart": "trendArea",
            "domainChartTitle": "库存策略域分布",
            "trendChartTitle": "近14天缺货与异常趋势",
            "kpis": [
                    {
                            "metric": "enabledRules",
                            "label": "已启用分析规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "缺货风险条数"
                    },
                    {
                            "metric": "healthScore",
                            "label": "库存健康分"
                    },
                    {
                            "metric": "autoFixRate",
                            "label": "参数自动更新率"
                    },
                    {
                            "metric": "domainLeadPending",
                            "label": "热点库存域"
                    },
                    {
                            "metric": "newAnomalies14d",
                            "label": "近14天新增异常"
                    }
            ],
            "tablePrefix": "inv-opt-"
    },
    "proc-audit-ai": {
            "appId": "proc-audit-ai",
            "template": "compliance-audit",
            "hue": 152,
            "icon": "audit",
            "healthScoreLabel": "合规健康分",
            "batchLabel": "检查批次",
            "heroChart": "riskDonut",
            "accentChart": "topRules",
            "domainChartTitle": "采购合规域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "合规检查规则"
                    },
                    {
                            "metric": "riskHigh",
                            "label": "高风险合规项"
                    },
                    {
                            "metric": "healthScore",
                            "label": "合规健康分"
                    },
                    {
                            "metric": "topRuleHits",
                            "label": "价格异常高发规则"
                    },
                    {
                            "metric": "checkRunsToday",
                            "label": "今日审查批次"
                    },
                    {
                            "metric": "rcaToday",
                            "label": "今日根因会话"
                    }
            ],
            "tablePrefix": "proc-audit-"
    },
    "ar-risk-ai": {
            "appId": "ar-risk-ai",
            "template": "finance",
            "hue": 32,
            "icon": "receivable",
            "healthScoreLabel": "风控健康分",
            "batchLabel": "检查批次",
            "heroChart": "agingStack",
            "accentChart": "riskDonut",
            "domainChartTitle": "应收账款账龄域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "enabledRules",
                            "label": "应收监控规则"
                    },
                    {
                            "metric": "highRiskPending",
                            "label": "高风险应收异常"
                    },
                    {
                            "metric": "healthScore",
                            "label": "风控健康分"
                    },
                    {
                            "metric": "domainLeadPending",
                            "label": "账龄最重业务域"
                    },
                    {
                            "metric": "resolvedShare",
                            "label": "异常闭环率"
                    },
                    {
                            "metric": "rcaSessions",
                            "label": "催收分析会话"
                    }
            ],
            "tablePrefix": "ar-risk-"
    },
    "ap-opt-ai": {
            "appId": "ap-opt-ai",
            "template": "finance",
            "hue": 262,
            "icon": "payable",
            "healthScoreLabel": "应付健康分",
            "batchLabel": "检查批次",
            "heroChart": "statusPie",
            "accentChart": "domainBars",
            "domainChartTitle": "应付优化域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "应付优化规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "付款/匹配异常"
                    },
                    {
                            "metric": "healthScore",
                            "label": "应付健康分"
                    },
                    {
                            "metric": "autoFixRate",
                            "label": "折扣建议采纳率"
                    },
                    {
                            "metric": "statusPending",
                            "label": "待处理发票项"
                    },
                    {
                            "metric": "checkRunsToday",
                            "label": "今日优化运行"
                    }
            ],
            "tablePrefix": "ap-opt-"
    },
    "mfg-var-ai": {
            "appId": "mfg-var-ai",
            "template": "operations",
            "hue": 0,
            "icon": "manufacturing",
            "healthScoreLabel": "成本健康分",
            "batchLabel": "分析批次",
            "heroChart": "batchStack",
            "accentChart": "trendArea",
            "domainChartTitle": "生产成本域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "enabledRules",
                            "label": "成本偏差规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "工单偏差异常"
                    },
                    {
                            "metric": "healthScore",
                            "label": "成本健康分"
                    },
                    {
                            "metric": "topRuleHits",
                            "label": "超耗高发规则"
                    },
                    {
                            "metric": "checkRunsToday",
                            "label": "今日分析批次"
                    },
                    {
                            "metric": "batchStackDone",
                            "label": "最近批次完成数"
                    }
            ],
            "tablePrefix": "mfg-var-"
    },
    "forecast-ai": {
            "appId": "forecast-ai",
            "template": "operations",
            "hue": 187,
            "icon": "forecast",
            "healthScoreLabel": "校准健康分",
            "batchLabel": "分析批次",
            "heroChart": "trendArea",
            "accentChart": "topRules",
            "domainChartTitle": "预测校准域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "预测校准规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "MAPE/偏差异常"
                    },
                    {
                            "metric": "healthScore",
                            "label": "校准健康分"
                    },
                    {
                            "metric": "newAnomalies14d",
                            "label": "近14天预测偏差"
                    },
                    {
                            "metric": "autoFixRate",
                            "label": "参数建议采纳率"
                    },
                    {
                            "metric": "rcaToday",
                            "label": "今日校准会话"
                    }
            ],
            "tablePrefix": "forecast-"
    },
    "mdm-quality-ai": {
            "appId": "mdm-quality-ai",
            "template": "compliance-audit",
            "hue": 239,
            "icon": "master-data",
            "healthScoreLabel": "质量健康分",
            "batchLabel": "检查批次",
            "heroChart": "domainQuadrant",
            "accentChart": "riskDonut",
            "domainChartTitle": "主数据四域质量分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "enabledRuleShare",
                            "label": "规则启用率"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "主数据缺陷条数"
                    },
                    {
                            "metric": "healthScore",
                            "label": "质量健康分"
                    },
                    {
                            "metric": "domainLeadPending",
                            "label": "最差主数据域"
                    },
                    {
                            "metric": "autoFixedCount",
                            "label": "已自动修复条数"
                    },
                    {
                            "metric": "disabledRules",
                            "label": "待启用规则"
                    }
            ],
            "tablePrefix": "mdm-quality-"
    },
    "asset-life-ai": {
            "appId": "asset-life-ai",
            "template": "operations",
            "hue": 84,
            "icon": "asset",
            "healthScoreLabel": "资产健康分",
            "batchLabel": "检查批次",
            "heroChart": "statusPie",
            "accentChart": "domainBars",
            "domainChartTitle": "资产全生命周期域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "资产台账规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "账实/折旧异常"
                    },
                    {
                            "metric": "healthScore",
                            "label": "资产健康分"
                    },
                    {
                            "metric": "riskHigh",
                            "label": "高风险资产项"
                    },
                    {
                            "metric": "autoFixedCount",
                            "label": "已建议处置条数"
                    },
                    {
                            "metric": "disabledRules",
                            "label": "未启用规则"
                    }
            ],
            "tablePrefix": "asset-life-"
    },
    "tax-compliance-ai": {
            "appId": "tax-compliance-ai",
            "template": "compliance-audit",
            "hue": 28,
            "icon": "tax",
            "healthScoreLabel": "税务健康分",
            "batchLabel": "检查批次",
            "heroChart": "riskDonut",
            "accentChart": "domainBars",
            "domainChartTitle": "税务合规域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "enabledRules",
                            "label": "税务校验规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "申报缺口条数"
                    },
                    {
                            "metric": "healthScore",
                            "label": "税务健康分"
                    },
                    {
                            "metric": "riskMedium",
                            "label": "中风险税项"
                    },
                    {
                            "metric": "autoFixRate",
                            "label": "建议采纳率"
                    },
                    {
                            "metric": "newAnomalies14d",
                            "label": "近14天新发现"
                    }
            ],
            "tablePrefix": "tax-compliance-"
    },
    "otif-ai": {
            "appId": "otif-ai",
            "template": "supply-chain",
            "hue": 201,
            "icon": "delivery",
            "healthScoreLabel": "交付健康分",
            "batchLabel": "巡检批次",
            "heroChart": "trendArea",
            "accentChart": "domainBars",
            "domainChartTitle": "交付与齐套域分布",
            "trendChartTitle": "近14天 OTIF 相关异常趋势",
            "kpis": [
                    {
                            "metric": "enabledRules",
                            "label": "交付监控规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "交付异常条数"
                    },
                    {
                            "metric": "healthScore",
                            "label": "交付健康分"
                    },
                    {
                            "metric": "runningCheckRuns",
                            "label": "运行中巡检"
                    },
                    {
                            "metric": "resolved14d",
                            "label": "近14天已闭环"
                    },
                    {
                            "metric": "riskHigh",
                            "label": "高风险交付项"
                    }
            ],
            "tablePrefix": "otif-"
    },
    "quality-rca-ai": {
            "appId": "quality-rca-ai",
            "template": "compliance-audit",
            "hue": 343,
            "icon": "quality",
            "healthScoreLabel": "质量健康分",
            "batchLabel": "检查批次",
            "heroChart": "topRules",
            "accentChart": "riskDonut",
            "domainChartTitle": "质量追溯域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "质量追溯规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "批次/客诉异常"
                    },
                    {
                            "metric": "healthScore",
                            "label": "质量健康分"
                    },
                    {
                            "metric": "riskHigh",
                            "label": "高风险质量项"
                    },
                    {
                            "metric": "batchStackFailed",
                            "label": "检查失败批次"
                    },
                    {
                            "metric": "rcaSessions",
                            "label": "RCA 追溯会话"
                    }
            ],
            "tablePrefix": "quality-rca-"
    },
    "hr-compliance-ai": {
            "appId": "hr-compliance-ai",
            "template": "compliance-audit",
            "hue": 271,
            "icon": "hr",
            "healthScoreLabel": "合规健康分",
            "batchLabel": "检查批次",
            "heroChart": "domainBars",
            "accentChart": "riskDonut",
            "domainChartTitle": "人力合规域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "人力合规规则"
                    },
                    {
                            "metric": "highRiskPending",
                            "label": "高风险人力项"
                    },
                    {
                            "metric": "healthScore",
                            "label": "合规健康分"
                    },
                    {
                            "metric": "domainLeadPending",
                            "label": "重点合规域"
                    },
                    {
                            "metric": "checkRunTotal",
                            "label": "累计检查批次"
                    },
                    {
                            "metric": "rcaToday",
                            "label": "今日咨询会话"
                    }
            ],
            "tablePrefix": "hr-compliance-"
    },
    "project-health-ai": {
            "appId": "project-health-ai",
            "template": "project-service",
            "hue": 174,
            "icon": "project",
            "healthScoreLabel": "项目健康分",
            "batchLabel": "分析批次",
            "heroChart": "batchTimeline",
            "accentChart": "domainBars",
            "domainChartTitle": "项目交付域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "enabledRules",
                            "label": "项目监控规则"
                    },
                    {
                            "metric": "highRiskPending",
                            "label": "延误/超支风险"
                    },
                    {
                            "metric": "healthScore",
                            "label": "项目健康分"
                    },
                    {
                            "metric": "domainLeadPending",
                            "label": "最差项目域"
                    },
                    {
                            "metric": "checkRunsToday",
                            "label": "今日健康分析"
                    },
                    {
                            "metric": "rcaSessions",
                            "label": "交付复盘会话"
                    }
            ],
            "tablePrefix": "project-health-"
    },
    "energy-carbon-ai": {
            "appId": "energy-carbon-ai",
            "template": "sustainability",
            "hue": 142,
            "icon": "energy",
            "healthScoreLabel": "能源健康分",
            "batchLabel": "分析批次",
            "heroChart": "domainEsgBars",
            "accentChart": "trendArea",
            "domainChartTitle": "能源与碳排域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "能耗监控规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "能耗/碳排异常"
                    },
                    {
                            "metric": "healthScore",
                            "label": "能源健康分"
                    },
                    {
                            "metric": "domainLeadPending",
                            "label": "超标最重站点域"
                    },
                    {
                            "metric": "newAnomalies14d",
                            "label": "近14天能耗异常"
                    },
                    {
                            "metric": "autoFixRate",
                            "label": "节能建议采纳率"
                    }
            ],
            "tablePrefix": "energy-carbon-"
    },
    "contract-ai": {
            "appId": "contract-ai",
            "template": "project-service",
            "hue": 231,
            "icon": "contract",
            "healthScoreLabel": "履约健康分",
            "batchLabel": "检查批次",
            "heroChart": "recentBatches",
            "accentChart": "riskDonut",
            "domainChartTitle": "合同履约域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "合同履约规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "到期/SLA 异常"
                    },
                    {
                            "metric": "healthScore",
                            "label": "履约健康分"
                    },
                    {
                            "metric": "riskHigh",
                            "label": "高风险合同"
                    },
                    {
                            "metric": "checkRunTotal",
                            "label": "累计巡检批次"
                    },
                    {
                            "metric": "resolvedShare",
                            "label": "履约闭环率"
                    }
            ],
            "tablePrefix": "contract-"
    },
    "channel-inv-ai": {
            "appId": "channel-inv-ai",
            "template": "supply-chain",
            "hue": 38,
            "icon": "channel",
            "healthScoreLabel": "协同健康分",
            "batchLabel": "分析批次",
            "heroChart": "domainBars",
            "accentChart": "riskDonut",
            "domainChartTitle": "渠道库存域分布",
            "trendChartTitle": "近14天渠道异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "渠道监控规则"
                    },
                    {
                            "metric": "highRiskPending",
                            "label": "高风险渠道异常"
                    },
                    {
                            "metric": "healthScore",
                            "label": "协同健康分"
                    },
                    {
                            "metric": "pendingShare",
                            "label": "待处理占比"
                    },
                    {
                            "metric": "checkRunsToday",
                            "label": "今日协同分析"
                    },
                    {
                            "metric": "topRuleHits",
                            "label": "高发规则命中"
                    }
            ],
            "tablePrefix": "channel-inv-"
    },
    "budget-control-ai": {
            "appId": "budget-control-ai",
            "template": "finance",
            "hue": 172,
            "icon": "budget",
            "healthScoreLabel": "预算健康分",
            "batchLabel": "检查批次",
            "heroChart": "domainBars",
            "accentChart": "statusPie",
            "domainChartTitle": "预算执行域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "ruleCount",
                            "label": "预算监控规则"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "超支/无预算项"
                    },
                    {
                            "metric": "healthScore",
                            "label": "预算健康分"
                    },
                    {
                            "metric": "domainLeadPending",
                            "label": "超支最重部门域"
                    },
                    {
                            "metric": "autoFixRate",
                            "label": "冻结建议采纳率"
                    },
                    {
                            "metric": "runningCheckRuns",
                            "label": "运行中监控"
                    }
            ],
            "tablePrefix": "budget-control-"
    },
    "service-sla-ai": {
            "appId": "service-sla-ai",
            "template": "project-service",
            "hue": 213,
            "icon": "service",
            "healthScoreLabel": "SLA 健康分",
            "batchLabel": "巡检批次",
            "heroChart": "riskDonut",
            "accentChart": "batchTimeline",
            "domainChartTitle": "售后服务域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "pendingAnomalies",
                            "label": "SLA 违约条数"
                    },
                    {
                            "metric": "riskHigh",
                            "label": "P1 级超时风险"
                    },
                    {
                            "metric": "healthScore",
                            "label": "SLA 健康分"
                    },
                    {
                            "metric": "checkRunsToday",
                            "label": "今日巡检批次"
                    },
                    {
                            "metric": "resolved14d",
                            "label": "近14天已闭环"
                    },
                    {
                            "metric": "topRuleHits",
                            "label": "重复维修高发规则"
                    }
            ],
            "tablePrefix": "service-sla-"
    },
    "fx-risk-ai": {
            "appId": "fx-risk-ai",
            "template": "finance",
            "hue": 258,
            "icon": "fx",
            "healthScoreLabel": "外汇健康分",
            "batchLabel": "检查批次",
            "heroChart": "trendArea",
            "accentChart": "riskDonut",
            "domainChartTitle": "外汇风险域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "enabledRules",
                            "label": "外汇监控规则"
                    },
                    {
                            "metric": "riskHigh",
                            "label": "敞口高风险项"
                    },
                    {
                            "metric": "healthScore",
                            "label": "外汇健康分"
                    },
                    {
                            "metric": "riskMedium",
                            "label": "中风险汇兑项"
                    },
                    {
                            "metric": "newAnomalies14d",
                            "label": "近14天新增预警"
                    },
                    {
                            "metric": "rcaSessions",
                            "label": "对冲分析会话"
                    }
            ],
            "tablePrefix": "fx-risk-"
    },
    "esg-report-ai": {
            "appId": "esg-report-ai",
            "template": "sustainability",
            "hue": 128,
            "icon": "esg",
            "healthScoreLabel": "ESG 健康分",
            "batchLabel": "检查批次",
            "heroChart": "domainEsgBars",
            "accentChart": "statusPie",
            "domainChartTitle": "ESG 披露域分布",
            "trendChartTitle": "近14天异常趋势",
            "kpis": [
                    {
                            "metric": "enabledRuleShare",
                            "label": "披露规则启用率"
                    },
                    {
                            "metric": "pendingAnomalies",
                            "label": "披露缺口条数"
                    },
                    {
                            "metric": "healthScore",
                            "label": "ESG 健康分"
                    },
                    {
                            "metric": "domainLeadPending",
                            "label": "ESG 薄弱域"
                    },
                    {
                            "metric": "resolvedShare",
                            "label": "披露完整率(闭环)"
                    },
                    {
                            "metric": "rcaSessions",
                            "label": "披露编报会话"
                    }
            ],
            "tablePrefix": "esg-report-"
    },
};

export function getEnterpriseDashboardConfig(appId: string): EnterpriseDashboardConfig | undefined {
    return ENTERPRISE_DASHBOARD_BY_APP_ID[appId];
}
