/**
 * Per-app dashboard theme presets (20 enterprise apps, excludes ehcs-ai).
 */
export const DASHBOARD_TEMPLATE_IDS = [
    "supply-chain",
    "compliance-audit",
    "finance",
    "operations",
    "project-service",
    "sustainability",
];

/** @type {Record<string, import('./dashboard-presets.types').DashboardPreset>} */
export const DASHBOARD_PRESETS = {
    "inv-opt-ai": {
        template: "supply-chain",
        healthScoreLabel: "库存健康分",
        batchLabel: "分析批次",
        heroChart: "domainBars",
        accentChart: "trendArea",
        domainChartTitle: "库存策略域分布",
        trendChartTitle: "近14天缺货与异常趋势",
    },
    "channel-inv-ai": {
        template: "supply-chain",
        healthScoreLabel: "协同健康分",
        batchLabel: "分析批次",
        heroChart: "domainBars",
        accentChart: "riskDonut",
        domainChartTitle: "渠道库存域分布",
        trendChartTitle: "近14天渠道异常趋势",
    },
    "otif-ai": {
        template: "supply-chain",
        healthScoreLabel: "交付健康分",
        batchLabel: "巡检批次",
        heroChart: "trendArea",
        accentChart: "domainBars",
        domainChartTitle: "交付与齐套域分布",
        trendChartTitle: "近14天 OTIF 相关异常趋势",
    },
    "proc-audit-ai": {
        template: "compliance-audit",
        healthScoreLabel: "合规健康分",
        batchLabel: "检查批次",
        heroChart: "riskDonut",
        accentChart: "topRules",
        domainChartTitle: "采购合规域分布",
    },
    "mdm-quality-ai": {
        template: "compliance-audit",
        healthScoreLabel: "质量健康分",
        batchLabel: "检查批次",
        heroChart: "domainQuadrant",
        accentChart: "riskDonut",
        domainChartTitle: "主数据四域质量分布",
    },
    "quality-rca-ai": {
        template: "compliance-audit",
        healthScoreLabel: "质量健康分",
        batchLabel: "检查批次",
        heroChart: "topRules",
        accentChart: "riskDonut",
        domainChartTitle: "质量追溯域分布",
    },
    "tax-compliance-ai": {
        template: "compliance-audit",
        healthScoreLabel: "税务健康分",
        batchLabel: "检查批次",
        heroChart: "riskDonut",
        accentChart: "domainBars",
        domainChartTitle: "税务合规域分布",
    },
    "hr-compliance-ai": {
        template: "compliance-audit",
        healthScoreLabel: "合规健康分",
        batchLabel: "检查批次",
        heroChart: "domainBars",
        accentChart: "riskDonut",
        domainChartTitle: "人力合规域分布",
    },
    "ar-risk-ai": {
        template: "finance",
        healthScoreLabel: "风控健康分",
        batchLabel: "检查批次",
        heroChart: "agingStack",
        accentChart: "riskDonut",
        domainChartTitle: "应收账款账龄域分布",
    },
    "ap-opt-ai": {
        template: "finance",
        healthScoreLabel: "应付健康分",
        batchLabel: "检查批次",
        heroChart: "statusPie",
        accentChart: "domainBars",
        domainChartTitle: "应付优化域分布",
    },
    "fx-risk-ai": {
        template: "finance",
        healthScoreLabel: "外汇健康分",
        batchLabel: "检查批次",
        heroChart: "trendArea",
        accentChart: "riskDonut",
        domainChartTitle: "外汇风险域分布",
    },
    "budget-control-ai": {
        template: "finance",
        healthScoreLabel: "预算健康分",
        batchLabel: "检查批次",
        heroChart: "domainBars",
        accentChart: "statusPie",
        domainChartTitle: "预算执行域分布",
    },
    "mfg-var-ai": {
        template: "operations",
        healthScoreLabel: "成本健康分",
        batchLabel: "分析批次",
        heroChart: "batchStack",
        accentChart: "trendArea",
        domainChartTitle: "生产成本域分布",
    },
    "forecast-ai": {
        template: "operations",
        healthScoreLabel: "校准健康分",
        batchLabel: "分析批次",
        heroChart: "trendArea",
        accentChart: "topRules",
        domainChartTitle: "预测校准域分布",
    },
    "asset-life-ai": {
        template: "operations",
        healthScoreLabel: "资产健康分",
        batchLabel: "检查批次",
        heroChart: "statusPie",
        accentChart: "domainBars",
        domainChartTitle: "资产全生命周期域分布",
    },
    "project-health-ai": {
        template: "project-service",
        healthScoreLabel: "项目健康分",
        batchLabel: "分析批次",
        heroChart: "batchTimeline",
        accentChart: "domainBars",
        domainChartTitle: "项目交付域分布",
    },
    "contract-ai": {
        template: "project-service",
        healthScoreLabel: "履约健康分",
        batchLabel: "检查批次",
        heroChart: "recentBatches",
        accentChart: "riskDonut",
        domainChartTitle: "合同履约域分布",
    },
    "service-sla-ai": {
        template: "project-service",
        healthScoreLabel: "SLA 健康分",
        batchLabel: "巡检批次",
        heroChart: "riskDonut",
        accentChart: "batchTimeline",
        domainChartTitle: "售后服务域分布",
    },
    "energy-carbon-ai": {
        template: "sustainability",
        healthScoreLabel: "能源健康分",
        batchLabel: "分析批次",
        heroChart: "domainEsgBars",
        accentChart: "trendArea",
        domainChartTitle: "能源与碳排域分布",
    },
    "esg-report-ai": {
        template: "sustainability",
        healthScoreLabel: "ESG 健康分",
        batchLabel: "检查批次",
        heroChart: "domainEsgBars",
        accentChart: "statusPie",
        domainChartTitle: "ESG 披露域分布",
    },
};
